import React from "react";
import TextField from "@mui/material/TextField";
export function FormFields({ item, errors, handleInput }) {
  return (
    <>
      <TextField
        id="title"
        label="title"
        variant="outlined"
        value={item?.title}
        onChange={handleInput}
        error={Boolean(errors.title)}
        helperText={errors.title}
      />
      <TextField
        id="description"
        label="description"
        variant="outlined"
        value={item?.description}
        onChange={handleInput}
        error={Boolean(errors.description)}
        helperText={errors.description}
      />
      <TextField
        id="subtitle"
        label="subtitle"
        variant="outlined"
        value={item?.subtitle}
        onChange={handleInput}
        error={Boolean(errors.subtitle)}
        helperText={errors.subtitle}
      />
      <TextField
        id="phone"
        label="phone"
        variant="outlined"
        value={item?.phone}
        onChange={handleInput}
        error={Boolean(errors.phone)}
        helperText={errors.phone}
      />
      <TextField
        id="email"
        label="email"
        variant="outlined"
        value={item?.email}
        onChange={handleInput}
        error={Boolean(errors.email)}
        helperText={errors.email}
      />
      <TextField
        id="web"
        label="web"
        variant="outlined"
        value={item?.web}
        onChange={handleInput}
        error={Boolean(errors.web)}
        helperText={errors.web}
      />
      <TextField
        id="imgUrl"
        label="imgUrl"
        variant="outlined"
        value={item?.imgUrl}
        onChange={handleInput}
        error={Boolean(errors.imgUrl)}
        helperText={errors.imgUrl}
      />
      <TextField
        id="imgAlt"
        label="imgAlt"
        variant="outlined"
        value={item?.imgAlt}
        onChange={handleInput}
        error={Boolean(errors.imgAlt)}
        helperText={errors.imgAlt}
      />
      <TextField
        id="state"
        label="state"
        variant="outlined"
        value={item?.state}
        onChange={handleInput}
        error={Boolean(errors.state)}
        helperText={errors.state}
      />
      <TextField
        id="country"
        label="country"
        variant="outlined"
        value={item?.country}
        onChange={handleInput}
        error={Boolean(errors.country)}
        helperText={errors.country}
      />
      <TextField
        id="city"
        label="city"
        variant="outlined"
        value={item?.city}
        onChange={handleInput}
        error={Boolean(errors.city)}
        helperText={errors.city}
      />
      <TextField
        id="street"
        label="street"
        variant="outlined"
        value={item?.street}
        onChange={handleInput}
        error={Boolean(errors.street)}
        helperText={errors.street}
      />
      <TextField
        id="houseNumber"
        label="houseNumber"
        variant="outlined"
        value={item?.houseNumber}
        onChange={handleInput}
        error={Boolean(errors.houseNumber)}
        helperText={errors.houseNumber}
      />
      <TextField
        id="zip"
        label="zip"
        variant="outlined"
        value={item?.zip}
        onChange={handleInput}
        error={Boolean(errors.zip)}
        helperText={errors.zip}
      />
    </>
  );
}
